# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='name')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('image', models.ImageField(upload_to='uploads/authors/')),
                ('facebook_url', models.CharField(max_length=255, verbose_name='facebook')),
                ('twitter_url', models.CharField(max_length=255, verbose_name='twitter')),
                ('instagram_url', models.CharField(max_length=255, verbose_name='instagram')),
                ('linkedin_url', models.CharField(max_length=255, verbose_name='linkedin')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('body', models.TextField(verbose_name='message')),
                ('image', models.ImageField(upload_to='uploads/blogs/')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='blog.Author')),
            ],
        ),
    ]
