# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170829_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='name')),
                ('image', models.ImageField(upload_to='media/author/')),
                ('facebook_url', models.CharField(max_length=255, verbose_name='facebook')),
                ('twitter_url', models.CharField(max_length=255, verbose_name='facebook')),
                ('instagram_url', models.CharField(max_length=255, verbose_name='facebook')),
                ('linkedin_url', models.CharField(max_length=255, verbose_name='facebook')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Author'),
        ),
    ]
