# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_author_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='instagram_url',
            field=models.CharField(max_length=255, verbose_name='instagram'),
        ),
        migrations.AlterField(
            model_name='author',
            name='linkedin_url',
            field=models.CharField(max_length=255, verbose_name='linkedin'),
        ),
        migrations.AlterField(
            model_name='author',
            name='twitter_url',
            field=models.CharField(max_length=255, verbose_name='twitter'),
        ),
    ]
