# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='is_lab',
            field=models.BooleanField(default=False),
        ),
    ]
