# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_auto_20170924_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='code',
            field=models.CharField(db_index=True, default=12345, max_length=255, verbose_name='code'),
            preserve_default=False,
        ),
    ]
