# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_clinic_is_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
    ]
