# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-27 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_clinic_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
