# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_clinic_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
    ]
