# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_remove_city_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='code',
            field=models.CharField(db_index=True, max_length=6, verbose_name='code'),
        ),
    ]
