# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-13 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_clinic_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='image_thumb',
            field=models.ImageField(default='', upload_to='uploads/clinics/'),
            preserve_default=False,
        ),
    ]
