# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-26 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_clinic_image_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='image_thumb',
        ),
        migrations.AddField(
            model_name='clinic',
            name='banner_image_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
