# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-15 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_auto_20180226_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='banner_image_uploaded_at',
        ),
        migrations.AddField(
            model_name='clinic',
            name='image_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/clinics/thumbs/'),
        ),
    ]
