# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 20:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_remove_clinic_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='code',
            field=models.IntegerField(db_index=True, default=0, max_length=6, validators=[django.core.validators.RegexValidator('\\d{6,6}', 'Number must be 6 digits', 'Invalid number')], verbose_name='code'),
            preserve_default=False,
        ),
    ]
