# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 20:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_clinic_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='code',
            field=models.IntegerField(db_index=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='code'),
        ),
    ]
