# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_auto_20171021_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='code',
            field=models.CharField(db_index=True, max_length=6, unique=True, verbose_name='code'),
        ),
    ]
