# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_auto_20171101_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='website'),
        ),
    ]
