# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='qid')),
                ('start_datetime', models.DateTimeField(db_index=True)),
                ('end_datetime', models.DateTimeField(db_index=True)),
                ('duration', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, choices=[('CONF', 'CONFIRM'), ('PEND', 'PENDING'), ('NOSW', 'NOSHOW'), ('CANC', 'CANCEL')], db_index=True, default='PEND', max_length=4, verbose_name='status')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic', to='clinic.Clinic')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='name')),
            ],
        ),
    ]
