# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='recorded_datetime',
        ),
    ]
