# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20171109_1236'),
        ('clinic', '0001_initial'),
        ('appointment', '0002_auto_20171109_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_required', models.BooleanField(default=False)),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('prescription', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(choices=[(1, 'CONFIRM'), (2, 'PENDING'), (3, 'NOSHOW'), (4, 'CANCEL'), (5, 'DISCARD')], db_index=True, default=2, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='visit',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visit', to='appointment.Appointment'),
        ),
        migrations.AddField(
            model_name='visit',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='clinic.Clinic'),
        ),
        migrations.AddField(
            model_name='visit',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='person.Doctor'),
        ),
        migrations.AddField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='person.Patient'),
        ),
    ]
