# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_remove_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(choices=[(1, 'CONFIRM'), (2, 'PENDING'), (3, 'NOSHOW'), (4, 'CANCEL')], db_index=True, default=2, verbose_name='status'),
        ),
    ]
