# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-27 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_appointment_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(choices=[(1, 'CONFIRM'), (2, 'PENDING'), (3, 'NOSHOW'), (4, 'CANCEL'), (5, 'DISCARD'), (6, 'DONE')], db_index=True, default=2, verbose_name='status'),
        ),
    ]
