# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_auto_20171016_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentreason',
            old_name='title',
            new_name='name',
        ),
    ]
