# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
        ('person', '0002_auto_20171109_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(db_index=True, verbose_name='rating')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comment')),
                ('type', models.IntegerField(choices=[(1, 'DOCTOR'), (2, 'CLINIC')], verbose_name='type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='is_anonymous')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='clinic.Clinic')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='person.Patient')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='person.Doctor')),
            ],
        ),
    ]
