# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0006_auto_20170923_0714'),
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(db_index=True, max_length=50, verbose_name='degree')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_city', to='clinic.Country')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_clinic', to='clinic.Clinic')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_country', to='clinic.Country')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to='person.User')),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='name')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('martial_status', models.IntegerField(choices=[(1, 'MARRIED'), (2, 'SINGLE')], verbose_name='marital status')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_city', to='clinic.Country')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_country', to='clinic.Country')),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_occupation', to='profile_item.Occupation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to='person.User')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='name')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='name')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='services',
            field=models.ManyToManyField(related_name='doctor_services', to='profile_item.Service'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_specialization', to='profile_item.Specialization'),
        ),
    ]
