# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_item', '0002_auto_20170924_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorprofile',
            options={'verbose_name': 'Doctor Profile', 'verbose_name_plural': 'Doctor Profiles'},
        ),
    ]
