# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_item', '0003_auto_20170924_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to='person.User'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to='person.User'),
        ),
    ]
