# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_auto_20170924_1301'),
        ('profile_item', '0004_auto_20171004_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='clinic',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='clinic',
            field=models.ManyToManyField(related_name='doctor_clinics', to='clinic.Clinic'),
        ),
    ]
