# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_auto_20170924_1301'),
        ('profile_item', '0006_auto_20171006_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='clinic',
            field=models.ManyToManyField(related_name='patient_clinics', to='clinic.Clinic'),
        ),
    ]
