# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_item', '0007_patientprofile_clinic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprofile',
            old_name='martial_status',
            new_name='marital_status',
        ),
    ]
