# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_item', '0008_auto_20171006_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_city', to='clinic.City'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_country', to='clinic.Country'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='marital_status',
            field=models.IntegerField(blank=True, choices=[(1, 'MARRIED'), (2, 'SINGLE')], null=True, verbose_name='marital status'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='occupation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_occupation', to='profile_item.Occupation'),
        ),
    ]
