# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_item', '0009_auto_20171006_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='height'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='weight'),
        ),
    ]
