# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_item', '0009_auto_20171006_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(db_index=True)),
                ('end_datetime', models.DateTimeField(db_index=True)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_setting', to='profile_item.DoctorProfile')),
            ],
        ),
    ]
