# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_item', '0011_doctorsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsetting',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_setting', to='person.User'),
        ),
    ]
