# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profile_item', '0012_auto_20171015_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorsetting',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='doctorsetting',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='doctorsetting',
            name='end_time',
            field=models.TimeField(db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorsetting',
            name='start_time',
            field=models.TimeField(db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
