# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_item', '0013_auto_20171015_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_city', to='clinic.City'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_country', to='clinic.Country'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='degree',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='degree'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_specialization', to='profile_item.Specialization'),
        ),
    ]
