# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 10:01
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_item', '0014_auto_20171017_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorsetting',
            name='weekdays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=True), default=[True, True, True, True, True, True, True], size=7),
            preserve_default=False,
        ),
    ]
