# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 14:53
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_item', '0015_doctorsetting_weekdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorsetting',
            name='slot_duration',
            field=models.IntegerField(db_index=True, default=10),
        ),
        migrations.AlterField(
            model_name='doctorsetting',
            name='weekdays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=True), db_index=True, size=7),
        ),
    ]
