# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='name')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='phone')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='email')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('message', models.TextField(verbose_name='message')),
                ('contacted', models.BooleanField(db_index=True, default=False, verbose_name='contacted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
