# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0004_doctor_rating'),
        ('clinic', '0003_clinic_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='text')),
                ('type', models.IntegerField(choices=[(1, 'DOCTOR'), (2, 'PATIENT'), (3, 'ADMIN'), (4, 'GENERAL')], db_index=True, default=4, verbose_name='type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='clinic.Clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='person.Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='person.Patient')),
            ],
        ),
    ]
