# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-21 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_auto_20171208_1648'),
        ('notification', '0002_notification_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='person.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_notifications', to='clinic.Clinic'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_notifications', to='person.Doctor'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_notifications', to='person.Patient'),
        ),
    ]
