# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-22 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20171221_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='text',
        ),
        migrations.AddField(
            model_name='notification',
            name='content',
            field=models.CharField(default='', max_length=255, verbose_name='content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='heading',
            field=models.CharField(default='', max_length=255, verbose_name='heading'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'DOCTOR'), (2, 'PATIENT'), (3, 'ADMIN')], db_index=True, default=1, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.IntegerField(choices=[(1, 'APPOINTMENT'), (2, 'ANNOUNCEMENT')], db_index=True, default=2, verbose_name='type'),
        ),
    ]
