# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-26 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_auto_20171208_1648'),
        ('notification', '0004_auto_20171222_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderator_notifications', to='person.Moderator'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'DOCTOR'), (2, 'PATIENT'), (3, 'ADMIN')], db_index=True, default=1, verbose_name='user type'),
        ),
    ]
