# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-11 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_notification_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_notifications', to='clinic.Clinic'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_notifications', to='person.Doctor'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_notifications', to='person.Patient'),
        ),
    ]
