# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-11 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_auto_20180111_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(1, 'DOCTOR'), (2, 'PATIENT'), (3, 'ADMIN')], db_index=True, null=True, verbose_name='user type'),
        ),
    ]
