# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-06 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0008_auto_20180111_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='heading',
            field=models.TextField(verbose_name='heading'),
        ),
    ]
