# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='price')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('sample_required', models.CharField(max_length=255, verbose_name='sample')),
                ('is_common', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='clinic.Clinic')),
            ],
        ),
    ]
