# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorsetting',
            old_name='friday',
            new_name='friday_end',
        ),
        migrations.RenameField(
            model_name='doctorsetting',
            old_name='monday',
            new_name='friday_start',
        ),
        migrations.RenameField(
            model_name='doctorsetting',
            old_name='saturday',
            new_name='monday_end',
        ),
        migrations.RenameField(
            model_name='doctorsetting',
            old_name='sunday',
            new_name='monday_start',
        ),
        migrations.RenameField(
            model_name='doctorsetting',
            old_name='thursday',
            new_name='saturday_end',
        ),
        migrations.RenameField(
            model_name='doctorsetting',
            old_name='tuesday',
            new_name='saturday_start',
        ),
        migrations.RenameField(
            model_name='doctorsetting',
            old_name='wednesday',
            new_name='sunday_end',
        ),
        migrations.AddField(
            model_name='doctorsetting',
            name='sunday_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorsetting',
            name='thursday_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorsetting',
            name='thursday_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorsetting',
            name='tuesday_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorsetting',
            name='tuesday_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorsetting',
            name='wednesday_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorsetting',
            name='wednesday_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
