# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DR', 'DOCTOR'), ('PAT', 'PATIENT'), ('AD', 'ADMIN'), ('QAD', 'QADMIN')], max_length=3, verbose_name='role'),
        ),
    ]
