# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20171109_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='person.User')),
                ('role', models.IntegerField(default=3)),
            ],
            options={
                'abstract': False,
            },
            bases=('person.user',),
        ),
    ]
