# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20170922_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(db_index=True),
        ),
    ]
