# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
    ]
