# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_doctor_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='device_type',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
