# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_auto_20171208_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='device_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
