# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_auto_20170922_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(3, 'Unknown'), (2, 'Female'), (1, 'Male')], default=3, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'DOCTOR'), (2, 'PATIENT'), (3, 'ADMIN'), (4, 'QADMIN')], verbose_name='role'),
        ),
    ]
