# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-11 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_auto_20171208_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorHoliday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField()),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='person.Doctor')),
            ],
        ),
    ]
