# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-11 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_doctorholiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorholiday',
            name='day',
            field=models.DateField(),
        ),
    ]
