# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-11 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_auto_20180111_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorholiday',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
