# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-16 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0010_auto_20180111_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/avatars/thumbs'),
        ),
    ]
