# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-16 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_auto_20180315_1431'),
        ('person', '0011_user_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorsetting',
            name='clinic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='clinic.Clinic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctorsetting',
            name='physician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='person.Doctor'),
        ),
    ]
