# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0012_auto_20171021_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date of birth'),
        ),
    ]
