# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 19:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0013_auto_20171021_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default=datetime.datetime(2017, 10, 21, 19, 47, 8, 309826), verbose_name='date of birth'),
        ),
    ]
