# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 19:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0014_auto_20171021_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default=datetime.date(2017, 10, 21), verbose_name='date of birth'),
        ),
    ]
