# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 20:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0015_auto_20171021_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default=datetime.date(2017, 11, 1), verbose_name='date of birth'),
        ),
    ]
