# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        ('clinic', '0010_auto_20171101_2001'),
        ('person', '0017_auto_20171102_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='person.User')),
                ('degree', models.CharField(blank=True, max_length=50, null=True, verbose_name='degree')),
                ('services', models.ManyToManyField(related_name='doctor', to='resources.Service')),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='resources.Specialization')),
            ],
            options={
                'abstract': False,
            },
            bases=('person.user',),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='clinic.City'),
        ),
        migrations.AddField(
            model_name='user',
            name='clinic',
            field=models.ManyToManyField(related_name='user', to='clinic.Clinic'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='clinic.Country'),
        ),
    ]
