# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 08:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        ('person', '0019_remove_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='person.User')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='height')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='weight')),
                ('marital_status', models.IntegerField(blank=True, choices=[(1, 'MARRIED'), (2, 'SINGLE')], null=True, verbose_name='marital status')),
                ('occupation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='resources.Occupation')),
            ],
            options={
                'abstract': False,
            },
            bases=('person.user',),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default=datetime.date(2017, 11, 3), verbose_name='date of birth'),
        ),
    ]
