# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0020_auto_20171103_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='clinic',
            field=models.ManyToManyField(blank=True, null=True, related_name='user', to='clinic.Clinic'),
        ),
    ]
