# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0021_auto_20171103_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='role',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='patient',
            name='role',
            field=models.IntegerField(default=2),
        ),
    ]
