# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 13:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0022_auto_20171103_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='clinic',
            field=models.ManyToManyField(blank=True, related_name='user', to='clinic.Clinic'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default=datetime.date.today, verbose_name='date of birth'),
        ),
    ]
